name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
      - name: 'docker login'
        run: echo docker_vital | docker login -u 17032021 --password-stdin
      - name: "Build"
        run: docker build -t 17032012/diplom:latest .
      - name: "Push"
        run: docker push 17032012/diplom:latest .
